tours:
  newest_tours: 5
  hotest_tours: 6
  cheapest_tours: 6
  popular_places: 6
users:
  order_per_page: 10
reviews:
  per_pages_review: 10
  comment_per_page: 10
ckeditor:
  max_attachment_size: 100
  max_picture_size: 3
